services:
  - type: web
    name: TakeAFish-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

  - type: cron
    name: daily-report
    plan: free
    schedule: "0 9 * * *"   
    buildCommand: ""        
    startCommand: python daily_report.py
    envVars:
      - key: GOOGLE_CREDS_JSON
        sync: false
