name: Daily Fish Report

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  daily-report:
    runs-on: ubuntu-latest
    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
      REPORT_RECIPIENT: ${{ secrets.REPORT_RECIPIENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily report
        run: python services/dailyreport.py